title: Matthew Nutt
logo: ../assets/img/headshot_centered.jpg
description: Electrical & Computer Engineering Senior at Rice University
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
